name: golang-fmt
on:
  push:
    branches:
      - main
      - ci-dev # for testing
  pull_request:
    branches:
      - main
jobs:
  golang-fmt:
    name: gofmt
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: "."
          gofmt-flags: "-l -d"
        continue-on-error: true
      - name: Set status
        run: echo "gofmt-status=$?" >> $GITHUB_ENV
  golang-fix:
    needs: golang-fmt
    if: ${{ job.golang-fmt.outputs.gofmt-status > 0 }}
    name: gofmt-fix
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: "."
          gofmt-flags: "-w"
